# Jekyll configuration

lang: en
encoding: UTF-8
timezone: Europe/Paris

# Change value to match your needs if necessary
baseurl: /KAKUREMINO

# Website
title: KAKUREMINO
description: "KAKUREMINO is a very basic HTML template
created by Cedlog and powered by Jekyll"

author_license: "CC BY-SA 4.0"
author_license_url:
 "https://creativecommons.org/licenses/by-sa/4.0/legalcode.txt"

# Note: Github Pages only supports Kramdown !
markdown: kramdown
kramdown:
 auto_ids: false

# Note: Some of these files are excluded by default (eg Gemfile)
exclude:
- "Gemfile"
- "Gemfile.lock"
- "LICENSE"
- "README"