# *** Jekyll configuration ***
# The following elements are displayed in one line only: title, short_desc.
# This is because the header height must be explicit (overflow is hidden).

# Change values if not correct
baseurl: /KAKUREMINO
author: Cedlog
author_url: https://github.com/cedlog
title: KAKUREMINO
short_desc: A very basic and minimalist template for Jekyll
description: "KAKUREMINO is a minimalist basic
HTML template powered by Jekyll"
icon: favicon.png
lang: en
encoding: UTF-8
timezone: Europe/Paris

# Header menu items (3 items only / Header height is fixed).
# label: Item label.
# uri: Item URI (relative link).
item_0:
  label: "Home"
  uri:
item_1:
  label: "Preview"
  uri: preview.html
item_2:
  label: "About"
  uri: about.html

# Github metadata (Change values if not correct)
repository: username/repository

# Defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      # Theme style
      theme: "minimalist"
      # Layout style
      style: "kakuremino"
      app: "app"
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Cedlog"
      license: "CC BY-SA 4.0"
      license_url: https://creativecommons.org/licenses/by-sa/4.0/legalcode.txt

# Kramdown (Github Pages)
markdown: kramdown
kramdown:
 auto_ids: false

# Excluded files (All with same beginning pattern / Case sensitive)
exclude:
- "Gemfile"
- "README"
- "LICENSE"
- "LICENSING"